NAME_KEY = "name"
STATUS_KEY = "status"
HOURS_KEY = "hours"
PLATFORMS_KEY = "platforms"
GENRES_KEY = "genres"
STORES_KEY = "stores"
RELEASE_KEY = "release"
RELATED_KEY = "related"
TAGS_KEY = "tags"

FIELD_NAMES = [NAME_KEY, STATUS_KEY, HOURS_KEY, PLATFORMS_KEY, GENRES_KEY, STORES_KEY, RELEASE_KEY, RELATED_KEY, TAGS_KEY]